version: '3'

services:

    mariadb:
        image: mariadb:10.8.2
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=9YMSjf3DG2N4
            - MYSQL_USER=stelaj
            - MYSQL_DATABASE=stelaj
            - MYSQL_PASSWORD=2S5kYcY338td
        ports:
            - 9816:3306
        volumes:
            - mariadb_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=stelaj_mariadb
            - UPLOAD_LIMIT=5242880000
        ports:
            - 9815:80
volumes:
    mariadb_data:
